apiVersion: v1
kind: Service
metadata:
  name: weather-app
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007